

namespace Audiomata.ComponentTrackers
{
//-------------------------------------------------------------------------------------------------------------------------------
//					THIS CODE IS AUTOMATICALLY GENERATED, DO NOT MODIFY
//-------------------------------------------------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Audio;
using System.Collections.Generic;
using Audiomata;

 // Auto generated props, can use reflections but don't because it is REALLY slow
#region EnumeratedProps
 public enum AudioClipMembers
 {
	 }
#endregion

#region CommmandManager
 //Class to manage state of components
 public class AudioClipCommander :IAudioCommandable
 {
	private LimitedStack<AudioCommand<AudioClip> > audioCommands;
    public AudioClip Target{get;private set;}

    public object DoCommand<T>(T value, int enumeratedProp)
    {
        AudioCommand<AudioClip> newCommand = CommandFactory(enumeratedProp);
        newCommand.Do(value);
        audioCommands.Push(newCommand);
        return newCommand;
    }
    
    public object RegisterCommand(int enumeratedProp)
    {
        AudioCommand<AudioClip> newCommand = CommandFactory(enumeratedProp);
        audioCommands.Push(newCommand);
        return newCommand;
    }

    public void UndoCommand(object cmd)
    {
        AudioCommand<AudioClip> command = (AudioCommand<AudioClip>) cmd;
        command.Undo();
        audioCommands.Remove(command);
    }


    public void UndoLast()
    {
        if (audioCommands.Count<1)
        {
            return;
        }
        
        AudioCommand<AudioClip> popped = audioCommands.Pop();
        popped.Undo();
    }

    public void UndoAll()
    {
        while (audioCommands.Count>0)
        {
            AudioCommand<AudioClip> popped = audioCommands.Pop();
            popped.Undo();
        }
    }

    public void ClearChangeHistory()
    {
        while (audioCommands.Count>0)
        {
            AudioCommand<AudioClip> popped = audioCommands.Pop();
        }
    }

    private AudioCommand<AudioClip>CommandFactory(int enumeratedProp)
    {
        AudioClipMembers commandPropTarget = ( AudioClipMembers ) enumeratedProp;
            AudioCommand<AudioClip> nextCommand;
        switch(commandPropTarget){
                default:
            return null; 
      }
    }
 }

#endregion

#region AutoGeneratedCommands
	#endregion
}


